import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {useState, useEffect} from 'react'
import Header from '../components/Header'

export default function Home() {
  const daysOfTheWeek: string[] = [
    'Sunday', 
    'Monday', 
    'Tuesday', 
    'Wednesday', 
    'Thursday', 
    'Friday', 
    'Saturday'
  ]

  const months31: number[] = [0,2,4,6,7,9,11]
  const months30: number[] = [3,5,8,10]
  

  const [year, setYear] = useState<number>(new Date().getFullYear());
  const [month, setMonth] = useState<number>(new Date().getMonth());

  const [days, setDays] = useState<number | undefined>();
  // Set the amount of days in the month to 31, 30, or 28 based on which month is selected in the <select> menu in the header
  useEffect(()=>{
    if(months31.includes(month)) {
      setDays(31)
    }
    else if (months30.includes(month)){
      setDays(30)
    }
    else setDays(28)
  },[month] )

  // Create array of dates to map through based on how many days are in the selected month
  const daysArray: (number | string)[] = []
  if(typeof days !== 'undefined'){
    for(let i = 1; i <= days; i++) daysArray.push(i)
  } 

  // Find which day the 1st of the month is
  let firstDayOfMonth: number | undefined;
  if(year && month) {
    firstDayOfMonth = new Date(year, month, 1).getDay()
    for(let i = 0; i<firstDayOfMonth; i++) daysArray.unshift('')
  }


  const handleInputChange = (e) => {
    const {name, value} = e.target   
    
        if(name === 'month') setMonth(parseInt(value))
        if(name === 'year') setYear(parseInt(value))
  }

  return (
    <div className={styles['home-page']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/calendar.svg" />
      </Head>
      <Header
        month={month}
        setMonth={setMonth}
        handleInputChange={handleInputChange}
      />
      <main className={styles.calendar}>
        <section className={styles.calendar}>
          <div className={styles['calendar__labels-section']}>
            {
            daysOfTheWeek.map(day => <div key={day} className={styles['calendar__labels']}>{day}</div>)
            }
          </div>
          <section className={styles['calendar__days-section']}>
            {
              daysArray.map((day,i) => <div className={styles['calendar__day']} key={i}>{day}</div>)
            }
          </section>
        </section>
      </main>

        
    </div>
  )
}
